# Generated by Django 4.1.7 on 2023-03-15 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Topic",
            new_name="myTopic",
        ),
    ]
